###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

# Default values for lsf master.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

global:
  lsf:
    worker: 
      replicas: 1
      cpu: "200m"
      memory: "200Mi"
    image:
      repository: "ibmcom/lsfce"
      tag: "10.1.0"
      pullPolicy: "IfNotPresent"
  storage:
    ## The name of the PersistentVolumeClaim to use.
    existingVolumeClaim: "lsf"

master:
  enableResourceConstraints: false
  resources:
    requests:
      cpu: 600m
      memory: 2048Mi
    limits:
      cpu: 600m
      memory: 2048Mi

mariadb:
  enableResourceConstraints: false
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi
  password: passw0rd
  image:
    repository: ibmcom/mariadb 
    tag: 10.2.19
